---
grails:
    profile: web
    codegen:
        defaultPackage: quoddy_grails3
    spring:
        transactionManagement:
            proxies: false
    web:
      servlet:
         path: /
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
server:
   session:
      timeout: 600
      
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
#dataSource:
#    pooled: true
#    jmxExport: true
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: ''
#    logSql: false
environments:
    development:
        quartz:
            autoStartup: false
        dataSource:
            dbCreate: update
            url: jdbc:postgresql:quoddy_dev
            pooled: true
            jmxExport: true
            driverClassName: org.postgresql.Driver
            username: postgres
            password: ''
            logSql: false
    test:
        dataSource:
            dbCreate: create-drop
            # url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            url: jdbc:postgresql:quoddy_test
            pooled: true
            jmxExport: true
            driverClassName: org.postgresql.Driver
            username: postgres
            password: ''
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql:quoddy
            pooled: true
            jmxExport: true
            driverClassName: org.postgresql.Driver
            username: postgres
            password: ''
            logSql: false
friends:
  backingStore: "localdb"
groups:
  backingStore: "localdb"
created:
  accounts:
    backingStore: "localdb"
    
quartz:
  autoStartup: false
  jdbcStore: true
  scheduler:
    instanceName: 'quoddy_scheduler'
    instanceId: 'AUTO'
  threadPool:
    class: 'org.quartz.simpl.SimpleThreadPool'
    threadCount: 25
    threadPriority: 5
  jobStore:
    misfireThreshold: 60000
    class: 'org.quartz.impl.jdbcjobstore.JobStoreTX'
    driverDelegateClass: 'org.quartz.impl.jdbcjobstore.PostgreSQLDelegate'    
    useProperties: false
    dataSource: 'development'
    tablePrefix: 'qrtz_'
    isClustered: true
    clusterCheckinInterval: 20000
  dataSource:
    development:
      driver: 'org.postgresql.Driver'
      URL: 'jdbc:postgresql:quoddy_dev'
      user: 'postgres'
      password: ''
      maxConnections: 10
jms:
    templates:
        standard:
           messageConverterBean: "messageConverter"
    adapters:
        standard:
           messageConverterBean: "messageConverter"
    converters:
        standard:
           meta:
              clazz: org.fogbeam.quoddy.jms.NoOpMessageConverter
    containers:
        standard:
           messageConverter: null
